IF EXISTS(
	SELECT * FROM SYS.OBJECTS 
	WHERE TYPE = 'U' AND NAME = 'EMPRESA_VALOR')
BEGIN 
	DROP TABLE EMPRESA_VALOR
END

IF EXISTS(
	SELECT * FROM SYS.OBJECTS 
	WHERE TYPE = 'U' AND NAME = 'EMPRESA')
BEGIN 
	DROP TABLE EMPRESA
END

IF EXISTS(
	SELECT * FROM SYS.OBJECTS 
	WHERE TYPE = 'U' AND NAME = 'SETOR')
BEGIN 
	DROP TABLE SETOR
END


CREATE TABLE SETOR
(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EMPRESA
(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	SIGLA VARCHAR(10),
	URL VARCHAR(100) NOT NULL,
	ID_SETOR INT FOREIGN KEY REFERENCES SETOR(ID)
);

CREATE TABLE EMPRESA_VALOR
(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	ID_EMPRESA INT NOT NULL FOREIGN KEY REFERENCES EMPRESA(ID),
	DATA_VALOR DATETIME NOT NULL,
	PRECO DECIMAL(30,6) NOT NULL,
	VARIACAO DECIMAL(30,6),
	VOLUME DECIMAL(30,6),
	VOLUME_REAL DECIMAL(30,6),
	VALOR_MERCADO DECIMAL(30,6),
	PL DECIMAL(30,6),
	EPS DECIMAL(30,6),
	VARIACAO_EPS DECIMAL(30,6),
	DIV_YIELD DECIMAL(30,6)
);


